"""Metadata definitions for all Repcut build plan prompts (00 to 13).

Derived from guide prompts.pdf and repo guide amendments.
"""

from pydantic import BaseModel, Field


class PromptMetadata(BaseModel):
    """Static metadata defining a build plan prompt."""

    id: str = Field(description="Two-digit prompt identifier (e.g. '00', '01')")
    name: str = Field(description="Short human-readable title")
    wave: str = Field(description="Wave title (e.g. 'Wave 0')")
    wave_number: int = Field(description="Numeric wave identifier (0 to 5)")
    summary: str = Field(description="One-line summary of what gets built")
    deliverables: list[str] = Field(description="List of key deliverables")
    human_review: bool = Field(description="Whether a human taste/gate review is required")
    human_review_type: str | None = Field(
        default=None, description="Details of human review checkpoint"
    )
    key_tech: list[str] = Field(description="Key technologies used")
    gate_command: str = Field(description="Make command to run verification gate")
    report_file: str = Field(description="Relative path to session report doc")
    estimated_timeline: str = Field(description="Realistic calendar time estimate")


PROMPTS_METADATA: list[PromptMetadata] = [
    PromptMetadata(
        id="00",
        name="Agent Harness",
        wave="Wave 0",
        wave_number=0,
        summary="Repository harness, subagents, prompt runner commands, safety rules & CI skeleton",
        deliverables=[
            "12 custom agent roles in .claude/agents/",
            "10 custom slash commands in .claude/commands/",
            "9 binding rules in .claude/rules/ (incl. secrets guard)",
            "8 reusable skills in .claude/skills/",
            "GitHub Actions CI workflows & gitleaks guard",
            "scripts/verify_00.sh gate script",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["git", "make", "bash", "gitleaks", "GitHub Actions"],
        gate_command="make verify-00",
        report_file="docs/reports/prompt-00.md",
        estimated_timeline="1 week (Wave 0 total)",
    ),
    PromptMetadata(
        id="01",
        name="Scaffold & Dev Env",
        wave="Wave 0",
        wave_number=0,
        summary="FastAPI engine + Next.js UI scaffold, env diagnostics, and build gates",
        deliverables=[
            "FastAPI engine with async GET /health endpoint",
            "Next.js 14 App Router UI scaffold with dark theme tokens",
            "scripts/check_env.py toolchain & hardware checker",
            "Makefile dev/test/lint/verify targets",
            "scripts/verify_01.sh gate script",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["FastAPI", "Next.js 14", "TypeScript", "Tailwind", "PyTorch/CUDA", "FFmpeg"],
        gate_command="make verify-01",
        report_file="docs/reports/prompt-01.md",
        estimated_timeline="1 week (Wave 0 total)",
    ),
    PromptMetadata(
        id="02",
        name="Upload, Media Library & Player UI",
        wave="Wave 1",
        wave_number=1,
        summary="Resumable chunked video upload, media metadata extraction, proxy player UI",
        deliverables=[
            "SQLite database schema (projects, media_files, jobs)",
            "POST /projects chunked upload endpoint with hash verification",
            "FFmpeg metadata extraction & H.264 proxy preview generator",
            "WebSocket live job progress updates (/ws/jobs)",
            "CapCut/Premiere-style UI editor shell & media library grid",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["Next.js", "FastAPI", "SQLite", "Alembic", "FFmpeg", "WebSocket"],
        gate_command="make verify-02",
        report_file="docs/reports/prompt-02.md",
        estimated_timeline="6-8 weeks (Wave 1 total)",
    ),
    PromptMetadata(
        id="03",
        name="Analysis Engine",
        wave="Wave 1",
        wave_number=1,
        summary="PySceneDetect scene detection, frame sampling, VLM tags & motion analysis",
        deliverables=[
            "PySceneDetect ContentDetector per media file",
            "Laplacian variance frame sampler (sharpest frame per scene)",
            "Gemini 2.0 Flash VLM client with SQLite caching & rate limiter",
            "Optical-flow motion energy & audio RMS energy scoring",
            "UI scene strip with lighting/content badges & energy sparklines",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["PySceneDetect", "Gemini 2.0 Flash", "OpenCV", "Optical Flow", "SQLite"],
        gate_command="make verify-03",
        report_file="docs/reports/prompt-03.md",
        estimated_timeline="6-8 weeks (Wave 1 total)",
    ),
    PromptMetadata(
        id="04",
        name="Grading Engine (Themes + Adaptive Color)",
        wave="Wave 1",
        wave_number=1,
        summary="3D LUT color grading, gym themes, adaptive white balance & exposure",
        deliverables=[
            "Pydantic 3D LUT theme schema & adaptation rules",
            "5 Gym Pack v1 themes (Moody, Hardstyle, Aesthetic, Old-School, Raw+)",
            "Pre-LUT adaptive color normalizer (white balance, exposure, noise)",
            "FFmpeg filtergraph builder for graded preview renders",
            "UI theme selector with live scene preview thumbnails & intensity slider",
        ],
        human_review=True,
        human_review_type="★ Taste Review: Grade quality on own gym footage",
        key_tech=["FFmpeg filtergraph", "3D LUT (.cube)", "Colour Science", "Pydantic"],
        gate_command="make verify-04",
        report_file="docs/reports/prompt-04.md",
        estimated_timeline="6-8 weeks (Wave 1 total)",
    ),
    PromptMetadata(
        id="05",
        name="Auto-Edit Engine (Cuts, Beat Sync & Music)",
        wave="Wave 1",
        wave_number=1,
        summary="Silence removal, beat detection, deterministic edit planner & voice ducking",
        deliverables=[
            "Music library analyzer (librosa BPM, beat grid & energy curves)",
            "VLM vibe & energy track recommendation ranker",
            "Silence & dead-space detector (Silero VAD + motion RMS)",
            "Pure-function deterministic edit planner (beat-aligned cuts)",
            "Voice-activity ducking & UI beat-marked timeline editor",
        ],
        human_review=True,
        human_review_type="★ Taste Review: Does auto-edit feel natural and beat-synced?",
        key_tech=["librosa", "Silero VAD", "FFmpeg", "Music Analysis"],
        gate_command="make verify-05",
        report_file="docs/reports/prompt-05.md",
        estimated_timeline="6-8 weeks (Wave 1 total)",
    ),
    PromptMetadata(
        id="06",
        name="Captions & Export Pipeline",
        wave="Wave 1",
        wave_number=1,
        summary="Whisper word-level transcription, animated captions, master export pipeline",
        deliverables=[
            "faster-whisper local GPU transcription with German/English auto-detect",
            "3 animated caption styles (Punch pop-on-beat, Classic subtitle, Minimal)",
            "Click-to-edit caption editor UI with word timing adjustments",
            "Master FFmpeg render pipeline (original res -> grade -> cuts -> music -> captions)",
            "Platform export presets (Reel 9:16, Square 1:1, Landscape 16:9)",
        ],
        human_review=True,
        human_review_type="★ WAVE 1 GATE: End-to-end magic core verification on real footage",
        key_tech=["faster-whisper", "ASS Subtitles", "FFmpeg", "Export Presets"],
        gate_command="make verify-06",
        report_file="docs/reports/prompt-06.md",
        estimated_timeline="6-8 weeks (Wave 1 total)",
    ),
    PromptMetadata(
        id="07",
        name="Hero Moments & AI Slow Motion",
        wave="Wave 2",
        wave_number=2,
        summary="Highlight detection & RIFE 2x slow-motion with SSIM confidence fallback",
        deliverables=[
            "Hero-moment scorer (motion peaks + audio plate slams + VLM context)",
            "RIFE 2x optical flow frame interpolation wrapper (GPU VRAM aware)",
            "SSIM artifact confidence gate (auto-reverts to normal speed if low quality)",
            "Beat-aligned slow-motion cuts integrated into edit planner",
            "Model download script for RIFE weights (data/models/)",
        ],
        human_review=False,
        human_review_type="Report only (SSIM confidence gate is objective)",
        key_tech=["RIFE", "PyTorch", "SSIM", "CUDA", "Motion Analysis"],
        gate_command="make verify-07",
        report_file="docs/reports/prompt-07.md",
        estimated_timeline="4-5 weeks (Wave 2 total)",
    ),
    PromptMetadata(
        id="08",
        name="Reference-Video Matching",
        wave="Wave 2",
        wave_number=2,
        summary="Extract color palette, pacing & caption style from reference clip",
        deliverables=[
            "Reference video upload and ingestion pipeline",
            "Color look extractor (lift/gamma/gain/saturation -> reusable Repcut Theme)",
            "Rhythm & pacing extractor (PySceneDetect cut frequency & beat ratio)",
            "Gemini caption style classifier for reference video text",
            "One-click UI flow: 'Match this reference' theme + pacing application",
        ],
        human_review=True,
        human_review_type="★ Taste Review: Does output resemble the reference video?",
        key_tech=["Color Transfer", "PySceneDetect", "Gemini API", "Statistical Analysis"],
        gate_command="make verify-08",
        report_file="docs/reports/prompt-08.md",
        estimated_timeline="4-5 weeks (Wave 2 total)",
    ),
    PromptMetadata(
        id="09",
        name="Hook Detection & Before/After Trust UI",
        wave="Wave 2",
        wave_number=2,
        summary="Auto-select first 2s hook teaser & draggable split-screen before/after slider",
        deliverables=[
            "Hook selection engine (hero score x visual impact sub-2s teaser placement)",
            "Hook candidate preview strip UI with one-tap swap",
            "Draggable split-screen before/after slider UI (original vs processed)",
            "'What Repcut did' human-readable processing summary panel",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["React Shader/Canvas UI", "Split-screen", "Edit Planner"],
        gate_command="make verify-09",
        report_file="docs/reports/prompt-09.md",
        estimated_timeline="4-5 weeks (Wave 2 total)",
    ),
    PromptMetadata(
        id="10",
        name="Edit Memory, Platform Versions & Gym IQ",
        wave="Wave 3",
        wave_number=3,
        summary="Learned style profile, YOLO subject-tracked re-framing & pose rep counter",
        deliverables=[
            "Style profile learner (aggregates taste_events into user style priors)",
            "YOLO person detection smoothed crop reframing (9:16, 1:1, 16:9)",
            "YOLO-pose joint-angle rep counter for gym hero segments",
            "Smart caption suggestions ('8 reps', exercise name from VLM)",
        ],
        human_review=True,
        human_review_type="★ Taste Review: Does learned profile match user preferences?",
        key_tech=["YOLOv8 / YOLO-pose", "Ultralytics", "SQLite", "Style Profile ML"],
        gate_command="make verify-10",
        report_file="docs/reports/prompt-10.md",
        estimated_timeline="5-6 weeks (Wave 3 total)",
    ),
    PromptMetadata(
        id="11",
        name="Conversational Edit Copilot",
        wave="Wave 3",
        wave_number=3,
        summary="In-app natural language chat assistant executing edit operations via Gemini",
        deliverables=[
            "Typed operation tool registry (set_theme, set_music_track, remove_cut, etc.)",
            "Gemini 2.0 Flash function-calling agent loop with system prompt guardrails",
            "Docked right-panel Chat UI with edit change cards & tap-to-undo",
            "Undo stack integration matching UI buttons and chat commands",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["Gemini Function Calling", "TypeScript", "React Chat UI", "Agent Loop"],
        gate_command="make verify-11",
        report_file="docs/reports/prompt-11.md",
        estimated_timeline="5-6 weeks (Wave 3 total)",
    ),
    PromptMetadata(
        id="12",
        name="Test, Eval & Quality-Gate Suite",
        wave="Wave 4",
        wave_number=4,
        summary="Consolidated test suite, Playwright E2E & product claims eval pipeline",
        deliverables=[
            "Consolidated test suite (pytest engine >=80% cov, vitest UI, Playwright E2E)",
            "scripts/eval_pipeline.py automated quality-gate evaluator",
            "Versioned test media fixtures (data/fixtures/)",
            "Scorecard generator outputting docs/reports/eval-latest.md",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["pytest", "vitest", "Playwright", "Eval Pipeline"],
        gate_command="make verify-12",
        report_file="docs/reports/prompt-12.md",
        estimated_timeline="1-2 weeks (Wave 4 total)",
    ),
    PromptMetadata(
        id="13",
        name="Deployment Path (Documented, Deferred)",
        wave="Wave 5",
        wave_number=5,
        summary="Cloud architecture documentation, cost model & SQLite->Postgres migration",
        deliverables=[
            "docs/deployment.md cloud architecture (Vercel + Render + Modal GPU)",
            "Cost model table (€ per exported minute across scale tiers)",
            "scripts/migrate_sqlite_pg.py tested migration script",
            "Config abstraction audit eliminating hardcoded local paths",
        ],
        human_review=False,
        human_review_type="Report only",
        key_tech=["Documentation", "Cloud Architecture", "PostgreSQL Migration"],
        gate_command="make verify-13",
        report_file="docs/reports/prompt-13.md",
        estimated_timeline="1 week (Wave 5 total)",
    ),
]
